### PR TITLE
Fix missing mapped files in prod mode

### LINKED ISSUE #1: When using hash name in prod mode
Issue is that the plugin dont handle correctly the mapped files in prod mode. It works great in dev mode but the problem is if we are using `js/[name].[contenthash].js` in prod mode (which is pretty common) to bump assets version, the compiled source filename is different from dev to prod.

### PR DESCRIPTION
**Pull request by alexsoluweb**
Fixes #1 
This PR ensures that all source files are properly mapped in map.json in production mode.

### CODE REVIEW

File: BundleOutputPlugin.js [hunk 1]
```diff
@@ -1,79 +1,89 @@
...
-    });
-    this.options = { cwd: cwd(), output: 'map.json', ...options };
-  }
+class BundleOutputPlugin
+{
+    constructor(options = {})
+    {
+        validate(schema, options, {
+            name: 'BundleOutputPlugin',
+            baseDataPath: 'options',
```
Comment (cpiber) [inline BundleOutputPlugin.js:19]: Any reason for changing `BundleOutputPlugin.name` to the hardcoded string? The idea is that the string always matches the class name, and I believe that was standard practice at that time

File: BundleOutputPlugin.js [hunk 2]
```diff
@@ -1,79 +1,89 @@
...
+    apply(compiler)
+    {
+        const pluginName = 'BundleOutputPlugin';
+        const { webpack } = compiler;
+        const { Compilation, NormalModule } = webpack;
+        const { RawSource } = webpack.sources;
 
-  /**
-   * @param {import('webpack').Compiler} compiler 
-   */
```
Comment (cpiber) [inline BundleOutputPlugin.js:29]: Why remove the type information?

**Review by cpiber — CHANGES_REQUESTED** [review]
Have some questions from a cursor look over it

Also, I doubt the tests still work with your changes, please update them as necessary

Real review will come tomorrow or two days later, depending on how busy I am

**Comment by alexsoluweb** [comment]
Well I did not pass it throught test since i dont have time right now for it. It's working great at my side duh. (tested with webpack 5.98.0).

File: BundleOutputPlugin.js (hunk 1 above)
Comment (alexsoluweb) [reply BundleOutputPlugin.js]: Lol... if you change the classname you need to update it there in any way. But ok :)

File: BundleOutputPlugin.js (hunk 2 above)
Comment (alexsoluweb) [reply BundleOutputPlugin.js:29]: Fixed!

File: BundleOutputPlugin.js (hunk 1 above)
Comment (cpiber) [reply BundleOutputPlugin.js]: The advantage is that refactoring tools will automatically change that - or if not, you get an error, since the old object does not exist

**Review by cpiber — APPROVED** [review]
Looks good to me! Thanks for your contribution!

Note that I added a few commits, mainly regarding the tests :) If you want to look through
